name: Auto approve

on:
  pull_request_target:
    types: [labeled]
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: (github.actor == 'scout-24-fizz-app[bot]' || github.actor == 'dependabot[bot]') && contains(github.event.pull_request.labels.*.name, 'dependencies')
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
