name: Auto approve JOB

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'ioanlucut' && contains(github.event.pull_request.labels.*.name, 'bes-auto-merge')
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: '${{ secrets.PAT_BES_PROJECTS }}'
          review-message: "Auto approved PR"
