name: 'LaTeX Leadsheet Songbook'

on:
  push:
    branches:
      - main
    paths:
      - 'leadsheets/trupe_lauda_si_inchinare/**'
      - 'LaTeX/songbook/**'
      - 'src/songToLeadsheetConverter.ts'
  workflow_dispatch:

permissions:
  contents: write # publishes the GitHub release

jobs:
  LaTeXSongbookRelease:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Fonts
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install --reinstall ttf-mscorefonts-installer
          sudo fc-cache -fv # Refresh the font cache

      - name: Verify Font Installation
        run: |
          fc-list | grep -i "georgia"

      - name: Use Node.js 24.x
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Run Build songbook TEX
        run: |
          npm ci && npm run songbook:convert
        env:
          CI: true

      - name: Compile BES Songbook LaTeX doc
        uses: xu-cheng/latex-action@e2f99d4b3685b0da93f97e1b86ad8fab81105098 # v3
        with:
          root_file: bes-songbook.tex
          working_directory: LaTeX/songbook/
          latexmk_use_xelatex: true

      - name: Generate Release Tag
        id: tag
        run: |
          release_tag="BES_Songbook_$(date +"%Y_%B_%d_%H-%M")"
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          files: 'LaTeX/songbook/bes-songbook.pdf'
          tag_name: ${{ steps.tag.outputs.release_tag }}
          fail_on_unmatched_files: true
          draft: false
          make_latest: true
          generate_release_notes: true
          body: Release al caietului de cântece BES ale trupelor de laudă și închinare (se face incremental, după fiecare schimbare în repository). Acceseaza-l [aici](https://drive.google.com/drive/folders/1zaxtSZnHy73DaQLCCqoNCZ0lJ11ClHBR).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GDrive
        uses: adityak74/google-drive-upload-git-action@935eccf4c2812e4d492c3d7c7ff59ca7520bf129
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS_ENCODED }}
          filename: 'LaTeX/songbook/bes-songbook.pdf'
          folderId: ${{ secrets.GDRIVE_SONGBOOKS_FOLDER_ID }} # Songbooks
          overwrite: 'true' # optional boolean
